"""empty message

Revision ID: fed3c94c7fa4
Revises: ba61d4d918c7
Create Date: 2021-05-10 07:27:20.066162

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fed3c94c7fa4"
down_revision = "ba61d4d918c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_user_subscriptions", sa.Column("min_age", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_user_subscriptions", "min_age")
    # ### end Alembic commands ###
